#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libffmpeg-stub
Version  : 2
Release  : 2
URL      : http://localhost/cgit/projects/libffmpeg-stub/snapshot/libffmpeg-stub-2.tar.gz
Source0  : http://localhost/cgit/projects/libffmpeg-stub/snapshot/libffmpeg-stub-2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: libffmpeg-stub-lib = %{version}-%{release}

%description
No detailed description available

%package lib
Summary: lib components for the libffmpeg-stub package.
Group: Libraries

%description lib
lib components for the libffmpeg-stub package.


%prep
%setup -q -n libffmpeg-stub-2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541350492
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1541350492
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libffmpeg.so.1
